stages:
- static-check
- build
- e2e
- deploy

# static check stage
lint:
  stage: static-check
  script: ./tbox lint
unit:
  stage: static-check
  script: ./tbox unit
codegen:
  stage: static-check
  script: ./tbox verify

# build stage
build:
  stage: build
  script:
  - ./tbox build

# e2e stage
e2e:
  stage: e2e
  script:
  - ./tbox e2e

# deploy stage for master (with latest)
deploy-latest:
  stage: deploy
  only:
    refs:
    - master
  script:
  - docker tag localhost:5000/kubevirt-image-service-exporter:canary quay.io/tmaxanc/kubevirt-image-service-exporter:latest
  - docker push quay.io/tmaxanc/kubevirt-image-service-exporter:latest

# deploy stage for release (with tag name)
deploy-release:
  stage: deploy
  only:
  - tags
  script:
  - docker tag localhost:5000/kubevirt-image-service-exporter:canary quay.io/tmaxanc/kubevirt-image-service-exporter:${CI_COMMIT_TAG}
  - docker push quay.io/tmaxanc/kubevirt-image-service-exporter:${CI_COMMIT_TAG}
